// Generated by Wrangler on Thu Jan 02 2025 02:01:59 GMT-0600 (Central Standard Time)
// by running `wrangler types`

interface Env {
	GOOGLE_REDIRECT_URI: "http://localhost:5173/googleredirect";
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	OPENAI_API_KEY: string;
	OPENAI_ORGANIZATION: string;
	R2: R2Bucket;
	DB: D1Database;
}
