// Generated by Wrangler on Thu Jan 02 2025 01:39:04 GMT-0600 (Central Standard Time)
// by running `wrangler types`

interface Env {
	GOOGLE_REDIRECT_URI: "https://todo-2lq.pages.dev/googleredirect";
	GOOGLE_CLIENT_ID: string;
	GOOGLE_CLIENT_SECRET: string;
	OPENAI_API_KEY: string;
	OPENAI_ORGANIZATION: string;
	R2: R2Bucket;
	DB: D1Database;
}
