// Generated by Wrangler on Wed Jan 01 2025 14:54:04 GMT-0600 (Central Standard Time)
// by running `wrangler types`

interface Env {
	GOOGLE_REDIRECT_URI: "https://todo-2lq.pages.dev/googleredirect";
	R2: R2Bucket;
	DB: D1Database;
}
