# Cloudflare pages requires a top level name attribute
name = "gallery"

# Cloudflare Pages will ignore wrangler.toml without this line
pages_build_output_dir = "./build/client"

# Fixes "no such module 'node:events'"
compatibility_flags = [ "nodejs_compat" ]

# Fixes "compatibility_flags cannot be specified without a compatibility_date"
compatibility_date = "2024-04-18"

[[d1_databases]]
binding = "DB" 
database_name = "todo_db"
database_id = "012e6e17-4415-4539-9711-2fbe2c126d15"
migrations_dir="./app/drizzle/migrations"

[vars]
GOOGLE_REDIRECT_URI="http://localhost:5173/googleredirect"
# GOOGLE_REDIRECT_URI="https://todo-2lq.pages.dev/googleredirect"



[[r2_buckets]]
binding = "R2"
bucket_name = "artworks"

